-- 코드를 작성해주세요

# WHERE NOT IN()

SELECT ITEM_ID,ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_NAME NOT IN(SELECT A.ITEM_NAME
                        FROM ITEM_INFO A JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
                        GROUP BY A.ITEM_NAME)
ORDER BY ITEM_ID DESC;
