# SELECT OUTS.ANIMAL_ID, OUTS.NAME
# FROM ANIMAL_OUTS OUTS
# LEFT JOIN ANIMAL_INS INS
# ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
# WHERE INS.ANIMAL_ID is NULL
# ORDER BY OUTS.ANIMAL_ID


SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.ANIMAL_ID