-- 코드를 입력하세요
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN (SELECT FLAVOR, TOTAL_ORDER, SHIPMENT_ID
     FROM JULY
     ) AS B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY A.TOTAL_ORDER+SUM(B.TOTAL_ORDER) DESC LIMIT 3;


# SELECT *
# FROM JULY
# SELECT FLAVOR, TOTAL_ORDER
# FROM JULY;

# SELECT A.FLAVOR, SUM(A.TOTAL_ORDER)
# FROM FIRST_HALF A
# JOIN (SELECT FLAVOR, TOTAL_ORDER
#      FROM JULY
#      ) AS B
# ON A.FLAVOR = B.FLAVOR
# GROUP BY A.FLAVOR
# ORDER BY