-- 코드를 작성해주세요
SELECT A.EMP_NO, B.EMP_NAME,
CASE 
    WHEN AVG(A.SCORE) >= 80 AND AVG(A.SCORE) < 90 THEN 'B'
    WHEN AVG(A.SCORE) >= 90 AND AVG(A.SCORE) < 96 THEN 'A'
    WHEN AVG(A.SCORE) >= 96 THEN 'S'
    ELSE 'C'
END AS GRADE
,
CASE 
    WHEN AVG(A.SCORE) >= 80 AND AVG(A.SCORE) < 90 THEN B.SAL * 0.1
    WHEN AVG(A.SCORE) >= 90 AND AVG(A.SCORE) < 96 THEN B.SAL * 0.15
    WHEN AVG(A.SCORE) >= 96 THEN B.SAL * 0.2
    ELSE 0
END AS BONUS
FROM HR_GRADE A JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO



