SELECT A.YEAR AS YEAR, A.MAX_SIZE-B.SIZE_OF_COLONY AS YEAR_DEV, B.ID
FROM (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS A 
JOIN ECOLI_DATA B ON A.YEAR = YEAR(B.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV
