# SELECT SUM(SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
# FROM HR_EMPLOYEES E INNER JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
# GROUP BY YEAR, EMP_NO
# HAVING G.YEAR = '2022'
# ORDER BY 1 DESC
# LIMIT 1;

SELECT SUM(B.SCORE) AS SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES A JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
GROUP BY B.EMP_NO, B.YEAR
HAVING B.YEAR = '2022'
ORDER BY SCORE DESC
LIMIT 1