-- 코드를 입력하세요
# SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
# FROM ICECREAM_INFO I JOIN FIRST_HALF F ON I.FLAVOR = F.FLAVOR
# GROUP BY I.INGREDIENT_TYPE

SELECT A.INGREDIENT_TYPE, SUM(B.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO A JOIN FIRST_HALF B ON A.FLAVOR = B.FLAVOR
GROUP BY  A.INGREDIENT_TYPE