# SELECT 
#         b.BOOK_ID as BOOK_ID ,
#         a.AUTHOR_NAME as AUTHOR_NAME,
#         DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK b
# LEFT JOIN AUTHOR a ON b.AUTHOR_ID = A.AUTHOR_ID
#     WHERE b.CATEGORY = '경제'
# ORDER BY b.PUBLISHED_DATE ASC;


# SELECT b.BOOK_ID AS BOOK_ID, a.AUTHOR_NAME AS AUTHOR_NAME,DATE_FORMAT(b.PUBLISHED_DATE,'%Y-%m-%d')AS PUBLISHED_DATE
# FROM BOOK b LEFT JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
# WHERE b.CATEGORY = '경제'
# ORDER BY b.PUBLISHED_DATE ASC;

SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY = '경제'
ORDER BY A.PUBLISHED_DATE ASC;
